config/routes.rb
	Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tags, only: [:index, :show]
  resources :indefinitions, only: [:index, :show]
  resources :variables, only: [:index, :show]
  resources :aventures, only: [:index, :show]
  resources :countries, only: [:index, :show]

	root 'static_pages#home_page'

  resources :variables do
    resources :aventures, only: [:index]
  end
  resources :tags do
    resources :aventures, only: [:index]
  end


	devise_for :users, :controllers => { registrations: 'registrations' }
	as :user do
  	get 'signin', to: 'devise/sessions#new', as: :signin
  	get 'signup', to: 'devise/registrations#new', as: :signup
  	delete 'signout', to: 'devise/sessions#destroy', as: :signout
	end

  # Rotue for elastic search
	get 'search', to: 'search#search', as: :search


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aventure.rb
# == Schema Information
#
# Table name: aventures
#
#  id                             :integer          not null, primary key
#  title                          :string
#  aventure_text                  :text
#  aventure_video                 :string
#  aventure_audio                 :string
#  aventure_portrait              :string
#  aventure_illu                  :string
#  created_at                     :datetime         not null
#  updated_at                     :datetime         not null
#  aventure_portrait_file_name    :string
#  aventure_portrait_content_type :string
#  aventure_portrait_file_size    :integer
#  aventure_portrait_updated_at   :datetime
#  first_name                     :text
#  last_name                      :text
#  age                            :integer
#

require 'elasticsearch/model'

class Aventure < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_and_belongs_to_many :indefinitions
  has_and_belongs_to_many :variables
  has_and_belongs_to_many :tags
  belongs_to :country

  has_attached_file :aventure_portrait, styles: { large: '480x600#', medium: '400x500#', thumb: '200x250#' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :aventure_portrait, content_type: /\Aimage\/.*\z/

  validates :title, :first_name, :last_name, :age, presence: { message: 'Ce champs ne doit pas être laissé vide !' }

  # settings index: { number_of_shards: 1 } do
  #   mappings dynamic: 'false' do
  #     indexes :title, analyzer: 'english'
  #     indexes :aventure_text, analyzer: 'english'
  #   end
  # end

end

# # Delete the previous articles index in Elasticsearch
# Aventure.__elasticsearch__.client.indices.delete index: Aventure.index_name rescue nil
#
# # Create the new index with the new mapping
# Aventure.__elasticsearch__.client.indices.create \
#   index: Aventure.index_name,
#   body: { settings: Aventure.settings.to_hash, mappings: Aventure.mappings.to_hash }


Aventure.import force: true

app/controllers/aventures_controller.rb
class AventuresController < ApplicationController
  before_action :set_aventure, only: [:show, :edit, :update, :destroy]

  # GET /aventures
  # GET /aventures.json
  def index
      @aventures = Aventure.all
  end

  # GET /aventures/1
  # GET /aventures/1.json
  def show
  end

  # GET /aventures/new
  def new
    @aventure = Aventure.new
  end

  # GET /aventures/1/edit
  def edit
  end

  # POST /aventures
  # POST /aventures.json
  def create
    @aventure = Aventure.new(aventure_params)

    respond_to do |format|
      if @aventure.save
        format.html { redirect_to @aventure, notice: 'Aventure was successfully created.' }
        format.json { render :show, status: :created, location: @aventure }
      else
        format.html { render :new }
        format.json { render json: @aventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aventures/1
  # PATCH/PUT /aventures/1.json
  def update
    respond_to do |format|
      if @aventure.update(aventure_params)
        format.html { redirect_to @aventure, notice: 'Aventure was successfully updated.' }
        format.json { render :show, status: :ok, location: @aventure }
      else
        format.html { render :edit }
        format.json { render json: @aventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aventures/1
  # DELETE /aventures/1.json
  def destroy
    @aventure.destroy
    respond_to do |format|
      format.html { redirect_to aventures_url, notice: 'Aventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_aventure
    @aventure = Aventure.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def aventure_params
    params.require(:aventure).permit(:title, :aventure_text, :aventure_video, :aventure_audio, :aventure_portrait, :aventure_illu, :first_name, :last_name, :age, variable_ids: [],tag_ids: [])
  end
end

app/helpers/aventures_helper.rb
module AventuresHelper
end

app/views/aventures/_form.html.erb
<%= form_for(aventure) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.error :title %>
  </div>
  <div class="field">
    <%= f.label "Prénom" %>
    <%= f.text_field :first_name, class: "form-control" %>
    <%= f.error :first_name %>
  </div>
  <div class="field">
    <%= f.label "Nom" %>
    <%= f.text_field :last_name, class: "form-control" %>
    <%= f.error :last_name %>
  </div>
  <div class="field">
    <%= f.label "Age" %>
    <%= f.text_field :age, class: "form-control" %>
    <%= f.error :age %>
  </div>

  <div class="field">
    <%= f.label :aventure_text %>
    <%= f.text_area :aventure_text, class: "tinymce"%>
    <%= tinymce %>
  </div>

  <div class="field">
    <%= f.label :aventure_video %>
    <%= f.text_field :aventure_video, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :aventure_audio %>
    <%= f.text_field :aventure_audio, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :aventure_portrait %>
    <%= f.file_field :aventure_portrait, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :aventure_illu %>
    <%= f.text_field :aventure_illu, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label "Tags"%>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_metier, {}, {class: "checkbox", :multiple=>true}) do |b|%>
      <%= b.label{b.check_box + b.text} %>
    <%end%>
  </div>
  <div class="field">
    <%= f.label "Variables attachées"%>
    <%= collection_check_boxes :aventure, :variable_ids, Variable.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aventures/edit.html.erb
<h1>Editing Aventure</h1>
<div class="container">
<%= render 'form', aventure: @aventure %>

<%= link_to 'Show', @aventure %> |
<%= link_to 'Back', aventures_path %>
</div>

app/views/aventures/index.html.erb
<p id="notice"><%= notice %></p>
<div class="portrait_gallery">
  <% @aventures.each do |aventure| %>
  <div class="gallery_img">
    <%= link_to image_tag(aventure.aventure_portrait.url(:thumb)), aventure %>
    <div class="btn btn-white"><%= link_to "découvrir", aventure %></div>
  </div>
  <% end %>
</div>

app/views/aventures/show.html.erb
<div class="container">
  <div class="row aventure_row">
    <div class="col-xs-12 col-md-4 left">

      <%= image_tag @aventure.aventure_portrait.url(:medium), class: "aventure_img" %>
      <div class="aventure_info">
        <%= @aventure.first_name %>
        <span id="last_n">
          <%= @aventure.last_name %></span>
        |
        <%= @aventure.age %> ans
        |
        <% if @aventure.country %>
        <%= link_to @aventure.country.name, @aventure.country %>
        <% end %>
      </div>

    </div>

    <div class="col-xs-12 col-md-6 col-md-offset-2 right">
      <h2 id="title">“<%= @aventure.title %>”</h2>
      <span class="date"><%= @aventure.created_at.strftime("%-d %b")%></span>
      <div class="aventure_text">
        <%= @aventure.aventure_text.html_safe %>
      </div>

      <%= @aventure.aventure_video %>
      <%= @aventure.aventure_audio %>
      <%= @aventure.aventure_illu %>
      <div class="label_container">
        <strong>Rattaché aux variables :</strong>
        <% @aventure.variables.each do |variable| %>
        <%= link_to variable.name.downcase!, variable_path(variable), class: "label" %>
        <% end %>
      </div>
      <div class="label_container">
        <strong>Rattaché aux métiers :</strong>
        <% @aventure.tags.each do |tag| %>
        <%= link_to tag.tag_metier.downcase!, tag_path(tag), class: "label" %>
        <% end %>
      </div>
    </div>

  </div>
</div>