config/routes.rb
	Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tags, only: [:index, :show]
  resources :indefinitions, only: [:index, :show]
  resources :variables, only: [:index, :show]
  resources :aventures, only: [:index, :show]
  resources :countries, only: [:index, :show]

	root 'static_pages#home_page'

  resources :variables do
    resources :aventures, only: [:index]
  end
  resources :tags do
    resources :aventures, only: [:index]
  end


	devise_for :users, :controllers => { registrations: 'registrations' }
	as :user do
  	get 'signin', to: 'devise/sessions#new', as: :signin
  	get 'signup', to: 'devise/registrations#new', as: :signup
  	delete 'signout', to: 'devise/sessions#destroy', as: :signout
	end

  # Rotue for elastic search
	get 'search', to: 'search#search', as: :search


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/indefinition.rb
# == Schema Information
#
# Table name: indefinitions
#
#  id         :integer          not null, primary key
#  name       :string
#  def        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Indefinition < ApplicationRecord
  has_and_belongs_to_many :aventures
  has_and_belongs_to_many :variables
  has_and_belongs_to_many :tags
end

app/controllers/indefinitions_controller.rb
class IndefinitionsController < ApplicationController
  before_action :set_indefinition, only: [:show, :edit, :update, :destroy]

  # GET /indefinitions
  # GET /indefinitions.json
  def index
    @indefinitions = Indefinition.all
  end

  # GET /indefinitions/1
  # GET /indefinitions/1.json
  def show
  end

  # GET /indefinitions/new
  def new
    @indefinition = Indefinition.new
  end

  # GET /indefinitions/1/edit
  def edit
  end

  # POST /indefinitions
  # POST /indefinitions.json
  def create
    @indefinition = Indefinition.new(indefinition_params)

    respond_to do |format|
      if @indefinition.save
        format.html { redirect_to @indefinition, notice: 'Indefinition was successfully created.' }
        format.json { render :show, status: :created, location: @indefinition }
      else
        format.html { render :new }
        format.json { render json: @indefinition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indefinitions/1
  # PATCH/PUT /indefinitions/1.json
  def update
    respond_to do |format|
      if @indefinition.update(indefinition_params)
        format.html { redirect_to @indefinition, notice: 'Indefinition was successfully updated.' }
        format.json { render :show, status: :ok, location: @indefinition }
      else
        format.html { render :edit }
        format.json { render json: @indefinition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indefinitions/1
  # DELETE /indefinitions/1.json
  def destroy
    @indefinition.destroy
    respond_to do |format|
      format.html { redirect_to indefinitions_url, notice: 'Indefinition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indefinition
      @indefinition = Indefinition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indefinition_params
      params.require(:indefinition).permit(:name, :def, variable_ids:[])
    end
end

app/helpers/indefinitions_helper.rb
module IndefinitionsHelper
end

app/views/indefinitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indefinitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Def</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indefinitions.each do |indefinition| %>
      <tr>
        <td><%= indefinition.name %></td>
        <td><%= indefinition.def %></td>
        <td><%= link_to 'Show', indefinition %></td>
        <td><%= link_to 'Edit', edit_indefinition_path(indefinition) %></td>
        <td><%= link_to 'Destroy', indefinition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indefinition', new_indefinition_path %>

app/views/indefinitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @indefinition.name %>
</p>

<p>
  <strong>Def:</strong>
  <%= @indefinition.def %>
</p>

<p>
  <% @indefinition.variables.each do |f|%>
    <%=link_to f.name, f%>
  <%end%>
</p>

<%= link_to 'Back', indefinitions_path %>