config/routes.rb
	Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tags, only: [:index, :show]
  resources :indefinitions, only: [:index, :show]
  resources :variables, only: [:index, :show]
  resources :aventures, only: [:index, :show]
  resources :countries, only: [:index, :show]

	root 'static_pages#home_page'

  resources :variables do
    resources :aventures, only: [:index]
  end
  resources :tags do
    resources :aventures, only: [:index]
  end


	devise_for :users, :controllers => { registrations: 'registrations' }
	as :user do
  	get 'signin', to: 'devise/sessions#new', as: :signin
  	get 'signup', to: 'devise/registrations#new', as: :signup
  	delete 'signout', to: 'devise/sessions#destroy', as: :signout
	end

  # Rotue for elastic search
	get 'search', to: 'search#search', as: :search


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :aventures
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :path)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for(country) do |f| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
    <svg class="countries"
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:cc="http://creativecommons.org/ns#"
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:svg="http://www.w3.org/2000/svg"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
        xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
        version="1.2"
        id="svg2"
        x="0px"
        y="0px"
        width="950px"
        height="620px"
        viewBox="0 0 950 620"
        xml:space="preserve"
        inkscape:version="0.91 r13725"
        sodipodi:docname="World_map_-_low_resolution.svg"><metadata id="metadata346"><rdf:RDF><cc:Work
        rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
        rdf:resource="http://purl.org/dc/dcmitype/StillImage" /></cc:Work></rdf:RDF></metadata><defs id="defs344" /><sodipodi:namedview
        pagecolor="#ffffff"
        bordercolor="#666666"
        borderopacity="1"
        objecttolerance="10"
        gridtolerance="10"
        guidetolerance="10"
        inkscape:pageopacity="0"
        inkscape:pageshadow="2"
        inkscape:window-width="1920"
        inkscape:window-height="980" id="namedview342"
        showgrid="false"
        inkscape:object-nodes="true"
        inkscape:snap-smooth-nodes="true"
        inkscape:snap-nodes="true"
        inkscape:object-paths="true"
        inkscape:zoom="1"
        inkscape:cx="248.04005"
        inkscape:cy="326.05286"
        inkscape:window-x="0"
        inkscape:window-y="34"
        inkscape:window-maximized="1"
        inkscape:current-layer="svg2"/>
        <% @countries.each do |country| %>
            <%= tag :path, d: country.path, onclick: 'window.location.href = \''+country_path(country)+'\'', title: country.name %>
        <% end %>
    </svg>
</div>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h2 class="variable_name">
      <%= @country.name.downcase! %>
    </h2>


  </div>
</div>
<div class="portrait_gallery">
  <% @country.aventures.each do |aventure| %>
  <div class="gallery_img">
    <%= link_to image_tag(aventure.aventure_portrait.url(:thumb)), aventure %>
    <div class="btn btn-white"><%= link_to "découvrir", aventure %></div>
  </div>
  <% end %>
</div>