config/routes.rb
	Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tags, only: [:index, :show]
  resources :indefinitions, only: [:index, :show]
  resources :variables, only: [:index, :show]
  resources :aventures, only: [:index, :show]
  resources :countries, only: [:index, :show]

	root 'static_pages#home_page'

  resources :variables do
    resources :aventures, only: [:index]
  end
  resources :tags do
    resources :aventures, only: [:index]
  end


	devise_for :users, :controllers => { registrations: 'registrations' }
	as :user do
  	get 'signin', to: 'devise/sessions#new', as: :signin
  	get 'signup', to: 'devise/registrations#new', as: :signup
  	delete 'signout', to: 'devise/sessions#destroy', as: :signout
	end

  # Rotue for elastic search
	get 'search', to: 'search#search', as: :search


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digitales</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">

          <div class="navbar-header">
            <%= link_to 'Digitales', root_path, class: "navbar-brand" %>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Aventures', aventures_path %></li>
              <li><%# link_to 'Indéfinitions', indefinitions_path %></li>
              <li><%= link_to 'Variables', variables_path %></li>
              <li><%= link_to 'Carte', countries_path %></li>
              <li><%= link_to 'Recherche', search_path %></li>

                <% if user_signed_in? %>
                <li><%=link_to current_user.email, edit_user_registration_path%></li>
                <li><%= link_to 'Déconnexion', signout_path, method: :delete%></li>
                <% if current_user.admin? %>
                <li><%= link_to 'Administration', rails_admin_path%></li>
                <% end %>
              <% else %>
                <li><%= link_to 'Connexion', signin_path%></li>
                <li><%= link_to 'Inscription', signup_path%></li>
                <% end %>
            </ul>
            </div>




      </nav>
    </header>
    <%= yield %>
  </body>
</html>